# connect and import data from a postgres server

In [12]:
import pandas as pd
from sqlalchemy import create_engine

engine=create_engine("postgresql://postgres:bleach#postgres@localhost:5433/film")

#table query
table_query=''' 
SELECT table_name FROM information_schema.tables
WHERE table_schema='public' AND table_type ='BASE TABLE';
'''

table_names=pd.read_sql(table_query,engine)['table_name'].to_list() #to_list will not work in a dataframe

dfs={}
for table in table_names:
    dfs[table]=pd.read_sql(f"select * from public.{table}",engine)

payment = dfs["payment"]
film = dfs["film"]
actor = dfs["actor"]
address = dfs["address"]
category = dfs["category"]
city = dfs["city"]
country = dfs["country"]
customer = dfs["customer"]
film_actor = dfs["film_actor"]
film_category = dfs["film_category"]
inventory = dfs["inventory"]
language = dfs["language"]
rental = dfs["rental"]
staff = dfs["staff"]
store = dfs["store"]

# for displaying the full table

In [13]:
customer

,customer_id,store_id,first_name,last_name,email,address_id,activebool,create_date,last_update,active
0,1,1,MARY,SMITH,MARY.SMITH@sakilacustomer.org,5,True,2020-02-14,2020-02-15 09:57:20+00:00,1
1,2,1,PATRICIA,JOHNSON,PATRICIA.JOHNSON@sakilacustomer.org,6,True,2020-02-14,2020-02-15 09:57:20+00:00,1
2,3,1,LINDA,WILLIAMS,LINDA.WILLIAMS@sakilacustomer.org,7,True,2020-02-14,2020-02-15 09:57:20+00:00,1
3,4,2,BARBARA,JONES,BARBARA.JONES@sakilacustomer.org,8,True,2020-02-14,2020-02-15 09:57:20+00:00,1
4,5,1,ELIZABETH,BROWN,ELIZABETH.BROWN@sakilacustomer.org,9,True,2020-02-14,2020-02-15 09:57:20+00:00,1
...,...,...,...,...,...,...,...,...,...,...
594,595,1,TERRENCE,GUNDERSON,TERRENCE.GUNDERSON@sakilacustomer.org,601,True,2020-02-14,2020-02-15 09:57:20+00:00,1
595,596,1,ENRIQUE,FORSYTHE,ENRIQUE.FORSYTHE@sakilacustomer.org,602,True,2020-02-14,2020-02-15 09:57:20+00:00,1
596,597,1,FREDDIE,DUGGAN,FREDDIE.DUGGAN@sakilacustomer.org,603,True,2020-02-14,2020-02-15 09:57:20+00:00,1
597,598,1,WADE,DELVALLE,WADE.DELVALLE@sakilacustomer.org,604,True,2020-02-14,2020-02-15 09:57:20+00:00,1
598,599,2,AUSTIN,CINTRON,AUSTIN.CINTRON@sakilacustomer.org,605,True,2020-02-14,2020-02-15 09:57:20+00:00,1

# order by columns

DataFrame.sort_values(
    by,
    axis=0,
    ascending=True,
    inplace=False,
    kind='quicksort',
    na_position='last',
    ignore_index=False,
    key=None
)

### by- not needed in series

| Parameter          | Description                                                                |
| ------------------ | -------------------------------------------------------------------------- |
| **`by`**           | Column or list of columns to sort by. **Required**.                        |
| **`axis`**         | Sort along which axis. `0` = index (rows), `1` = columns. Default is `0`.  |
| **`ascending`**    | Sort ascending vs. descending. Can be `True`/`False` or list of bools.     |
| **`inplace`**      | If `True`, modifies the original DataFrame. Default is `False`.            |
| **`kind`**         | Sorting algorithm: `'quicksort'`, `'mergesort'`, `'heapsort'`, `'stable'`. |
| **`na_position`**  | `'first'` puts NaNs at the beginning, `'last'` puts NaNs at the end.       |
| **`ignore_index`** | If `True`, the result will have a new index from 0, 1, …, n-1.             |
| **`key`**          | A function to transform the data before sorting.                           |

In [14]:
customer.sort_values(by=['first_name','last_name'],axis=0,ascending=[False,True],inplace=False,kind='mergesort',na_position='first',ignore_index=True,key=None)

,customer_id,store_id,first_name,last_name,email,address_id,activebool,create_date,last_update,active
0,479,1,ZACHARY,HITE,ZACHARY.HITE@sakilacustomer.org,484,True,2020-02-14,2020-02-15 09:57:20+00:00,1
1,174,2,YVONNE,WATKINS,YVONNE.WATKINS@sakilacustomer.org,178,True,2020-02-14,2020-02-15 09:57:20+00:00,1
2,190,2,YOLANDA,WEAVER,YOLANDA.WEAVER@sakilacustomer.org,194,True,2020-02-14,2020-02-15 09:57:20+00:00,1
3,212,2,WILMA,RICHARDS,WILMA.RICHARDS@sakilacustomer.org,216,True,2020-02-14,2020-02-15 09:57:20+00:00,1
4,219,2,WILLIE,HOWELL,WILLIE.HOWELL@sakilacustomer.org,223,True,2020-02-14,2020-02-15 09:57:20+00:00,1
...,...,...,...,...,...,...,...,...,...,...
594,389,1,ALAN,KAHN,ALAN.KAHN@sakilacustomer.org,394,True,2020-02-14,2020-02-15 09:57:20+00:00,1
595,217,2,AGNES,BISHOP,AGNES.BISHOP@sakilacustomer.org,221,True,2020-02-14,2020-02-15 09:57:20+00:00,1
596,525,2,ADRIAN,CLARY,ADRIAN.CLARY@sakilacustomer.org,531,True,2020-02-14,2020-02-15 09:57:20+00:00,1
597,367,1,ADAM,GOOCH,ADAM.GOOCH@sakilacustomer.org,372,True,2020-02-14,2020-02-15 09:57:20+00:00,1
598,375,2,AARON,SELBY,AARON.SELBY@sakilacustomer.org,380,True,2020-02-14,2020-02-15 09:57:20+00:00,1

# Distinct

DataFrame.drop_duplicates(
    subset=None,
    keep='first',
    inplace=False,
    ignore_index=False
)

| Parameter      | Description                                                              |
| -------------- | ------------------------------------------------------------------------ |
| `subset`       | Which column(s) to check for duplicates                                  |
| `keep`         | `'first'` (default), `'last'`, or `False` false will give true unique    |
| `inplace`      | Modify the original DataFrame                                            |
| `ignore_index` | Reset index in the returned DataFrame                                    |

### subset not needed in series

In [15]:
customer.drop_duplicates(subset=['store_id','active'],keep='first',inplace=False,ignore_index=True)

,customer_id,store_id,first_name,last_name,email,address_id,activebool,create_date,last_update,active
0,1,1,MARY,SMITH,MARY.SMITH@sakilacustomer.org,5,True,2020-02-14,2020-02-15 09:57:20+00:00,1
1,4,2,BARBARA,JONES,BARBARA.JONES@sakilacustomer.org,8,True,2020-02-14,2020-02-15 09:57:20+00:00,1
2,16,2,SANDRA,MARTIN,SANDRA.MARTIN@sakilacustomer.org,20,True,2020-02-14,2020-02-15 09:57:20+00:00,0
3,124,1,SHEILA,WELLS,SHEILA.WELLS@sakilacustomer.org,128,True,2020-02-14,2020-02-15 09:57:20+00:00,0

# count()
DataFrame.count(axis=0, numeric_only=False)

| Parameter      | Description                                                     |
| -------------- | --------------------------------------------------------------- |
| `axis=0`       | Count along **columns** (default) → gives **count per column**  |
| `axis=1`       | Count along **rows** → gives **count per row**                  |
| `numeric_only` | If `True`, includes only numeric columns (useful with `axis=0`) |

In [16]:
# true unique
payment.drop_duplicates(subset='amount',keep=False,ignore_index=True,inplace=False).shape[0]

3

# count() - len() - df.size - df.shape
| Function  | Counts what?                               |
| --------- | ------------------------------------------ |
| `count()` | **Non-null** values only                   |
| `len(df)` | Number of **rows**                         |
| `df.shape`| gives a tuple (no: of rows, no: ofcolumns) |
| `df.size` | **All cells** (rows × columns) |  -> size() clubed with groupby objects to know the rows with nans

# nunique()
df.nunique(axis=0, dropna=True)

| Parameter | Description                                                                 |
| --------- | --------------------------------------------------------------------------- |
| `axis`    | `0` (default): count unique values per **column**<br>`1`: count per **row** |
| `dropna`  | If `True`, ignore `NaN` values (default)                                    |
|           | If `False`, `NaN` is counted as a unique value                              |

In [17]:
payment.nunique(axis=0,dropna=False)

payment_id      16049
customer_id       599
staff_id            2
rental_id       16044
amount             19
payment_date    15817
dtype: int64

# value_counts()
Series.value_counts(normalize=False, dropna=True, ascending=False)
You call it on a Series, not on a full DataFrame.

| Parameter   | Description                                              |
| ----------- | -------------------------------------------------------- |
| `normalize` | If `True`, returns **proportions** instead of raw counts |
| `dropna`    | If `False`, includes NaN in the counts                   |
| `ascending` | Sort result in **ascending order**                       |

In [18]:
# value count for count filters
fe=payment['amount'].value_counts(normalize=False,dropna=False,ascending=True).reset_index()
fe.columns = ['amount', 'counter'] # renamed columns
fe.loc[fe['counter']==1,['amount']]

   amount
0    1.98
1    9.98
2    8.97

# set_index()
df.set_index('column_name', inplace=False, drop=True)

| Parameter | Description                                             |
| --------- | ------------------------------------------------------- |
| `inplace` | Modify original DataFrame or return new one             |
| `drop`    | If `True`, removes the column after setting it as index |

In [19]:
fe.set_index('amount',inplace=True,drop=True)

# reset_index()

| Parameter   | Description                                             |
| ----------- | ------------------------------------------------------- |
| `drop=True` | Drops the index completely, instead of moving to column |
| `inplace`   | Apply directly or return a new DataFrame                |

In [20]:
# reset_index
fe.reset_index(drop=False,inplace=True)
fe

    amount  counter
0     1.98        1
1     9.98        1
2     8.97        1
3     7.98        5
4     5.98        7
5     3.98        8
6    11.99       10
7     0.00       24
8    10.99      104
9     9.99      256
10    8.99      485
11    1.99      640
12    7.99      670
13    3.99     1109
14    6.99     1119
15    5.99     1299
16    0.99     2979
17    2.99     3542
18    4.99     3789

# value_count -> group count without groupBY

In [21]:
# Limit offset
payment['customer_id'].value_counts(normalize=False,dropna=False,ascending=False).reset_index().loc[4,'customer_id']

75